### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by olivinesguerra** [cyber-republic/react-native-elastos-wallet-core-demo#12]
Hi Guys,

I followed all the the instruction inside the Readme.md file and I still encounter this bug on iOS

react-native-cli: 2.0.1
react-native: 0.57.4

//Logs
Installing build/Build/Products/Debug-iphonesimulator/RNMainchainDemo.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNMainchainDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNMainchainDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:618:11)
    at Object.execFileSync (child_process.js:636:13)
    at Promise.then (/Users/olivinesguerra/Desktop/files/Elastos/elastos_demo/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
//Log End

--I'm using expo I did'nt experience this. 
-- I also do the react-native upgrade, react-native link and still the same.

Thanks :D

**Comment by ademcan** [comment]
Following our discussion on discord, this issue should be now fixed. Could you please confirm @olivinesguerra ?

**Comment by olivinesguerra** [comment]
already fixed. Thanks
