### ISSUE TITLE
Android Wallet Demo

### ISSUE THREAD

**Issue by andersalm** [cyber-republic/react-native-elastos-wallet-core-demo#14]
Who: Developers and early adopters
What: A wallet built with React Native Framework (wallet npm)
Why: To show how it works, from both a developer and end user perspective

To do:
 - [x] [front end](https://github.com/cyber-republic/react-native-elastos-wallet-core-demo/issues/15)
 - [x] mnemonic seed
 - [x] import seed
 - [x] see balance
 - [x] see last 5 transactions
 - [x] make transaction
 - [x] show public address

**Comment by EricDualc** [comment]
Awesome!
