### ISSUE TITLE
Front-end

### ISSUE THREAD

**Issue by andersalm** [cyber-republic/react-native-elastos-wallet-core-demo#15]
Who: End users
What: https://pr.to/MB8PCY/
Why: Makes it easy to use and pretty to look at. One step closer to mainstream adoption.

**Comment by olivinesguerra** [comment]
Noted.

**Comment by olivinesguerra** [comment]
@ademcan hi . where can I commit the code?

**Comment by andersalm** [comment]
@olivinesguerra please create a new branch, you can call it "front-end" for example, and commit the code there. then you can create a PR to master

**Comment by olivinesguerra** [comment]
I think that is the problem. I cannot create a branch here in Github. I think I need some permission?

**Comment by andersalm** [comment]
you have been invited to the organization by KP, please check your email and accept

**Comment by ademcan** [comment]
You have to create the branch in your own fork of the repository. You can then push your code and send a PR to the main repository.

**Comment by kpachhai** [comment]
I have added olivinesguerra to the team. So he should be able to create a branch directly and then send a PR to master after that.
